/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    articles: Article;
    doctors: Doctor;
    services: Service;
    feedbacks: Feedback;
    socials: Social;
    questions: Question;
    schedule: Schedule;
    'service-prices': ServicePrice;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    'service-prices': ServicePricesSelect<false> | ServicePricesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    siteSettings: SiteSetting;
    contacts: Contact;
    content: Content;
    workingHours: WorkingHour;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    content: ContentSelect<false> | ContentSelect<true>;
    workingHours: WorkingHoursSelect<false> | WorkingHoursSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  sections?:
    | (
        | {
            image: number | Media;
            alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro-1';
          }
        | {
            title: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro-2';
          }
        | {
            title: string;
            description: string;
            image: number | Media;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            title?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            title?: string | null;
            articlesCount?: number | null;
            showMoreLink?: boolean | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-grid';
          }
        | {
            title?: string | null;
            /**
             * Виберіть статті для відображення
             */
            articles: (number | Article)[];
            buttonText?: string | null;
            /**
             * Введіть посилання на сторінку блогу. Якщо посилання не введено, кнопка не відображатиметься.
             */
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-row';
          }
        | {
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feedbacks';
          }
        | {
            title?: string | null;
            description?: string | null;
            image?: (number | null) | Media;
            showImage?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'description';
          }
        | {
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'doctors';
          }
        | {
            backgroundImage?: (number | null) | Media;
            title?: string | null;
            description?: string | null;
            /**
             * Вмикає напівпрозорий білий фон поверх зображення для кращої читабельності тексту
             */
            showOverlay?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-hero';
          }
        | {
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prices';
          }
        | {
            title?: string | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-info';
          }
      )[]
    | null;
  /**
   * Наприклад: /blog або /about. Обов'язково починається з /
   */
  path: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  image: number | Media;
  status: 'draft' | 'published';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  name: string;
  photo: number | Media;
  position: string;
  experience: string;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  /**
   * Lucide icon name
   */
  icon?: string | null;
  iconImage?: (number | null) | Media;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  clientName: string;
  stars: number;
  content: string;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  title: string;
  username: string;
  link: string;
  /**
   * Lucide icon name
   */
  icon: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  days: string;
  hours: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-prices".
 */
export interface ServicePrice {
  id: number;
  title: string;
  price: string;
  serviceId: number | Service;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'socials';
        value: number | Social;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'schedule';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'service-prices';
        value: number | ServicePrice;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: number | PayloadKv;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        'intro-1'?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
        'intro-2'?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'blog-grid'?:
          | T
          | {
              title?: T;
              articlesCount?: T;
              showMoreLink?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        'blog-row'?:
          | T
          | {
              title?: T;
              articles?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        feedbacks?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              showImage?: T;
              id?: T;
              blockName?: T;
            };
        description?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        doctors?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'blog-hero'?:
          | T
          | {
              backgroundImage?: T;
              title?: T;
              description?: T;
              showOverlay?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        prices?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'contact-info'?:
          | T
          | {
              title?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
      };
  path?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  status?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  position?: T;
  experience?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  iconImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  clientName?: T;
  stars?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  title?: T;
  username?: T;
  link?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  days?: T;
  hours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-prices_select".
 */
export interface ServicePricesSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  serviceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Глобальні налаштування хедера, футера та навігації
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * SVG або PNG (рекомендовано SVG для чіткості)
   */
  logo: number | Media;
  /**
   * Використовується в хедері та футері
   */
  menuItems?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Відображається в хедері та мобільному меню
   */
  contactButtonText: string;
  showInHeader?: boolean | null;
  /**
   * Додатково до соц. мереж
   */
  showInMobileMenu?: boolean | null;
  /**
   * Текст над пунктами меню у футері
   */
  footerMenuTitle?: string | null;
  /**
   * Адреса та телефон з Global "Contacts"
   */
  showContactsInFooter?: boolean | null;
  /**
   * Дані з Global "Working Hours"
   */
  showWorkingHours?: boolean | null;
  workingHoursTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Clinic contact information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  address: string;
  addressMapLink: string;
  phone: string;
  addressLabel?: string | null;
  phoneLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content".
 */
export interface Content {
  id: number;
  navigationMenu: {
    home: string;
    doctors: string;
    services: string;
    feedbacks: string;
    blog: string;
    prices: string;
  };
  homePage: {
    welcomeImage?: (number | null) | Media;
    welcomeDescription: string;
    aboutImage?: (number | null) | Media;
    aboutTitle: string;
    aboutDescription: string;
    missionTitle: string;
    missionDescription: string;
    servicesTitle: string;
    servicesDescription: string;
    ctaTitle: string;
    ctaDescription: string;
    feedbacksTitle: string;
    blogTitle: string;
    blogButton: string;
    contactTitle: string;
  };
  doctorsPage: {
    pageTitle: string;
    pageDescription: string;
  };
  blogPage: {
    backgroundImage?: (number | null) | Media;
    pageTitle: string;
    pageDescription: string;
    articlesTitle: string;
    faqTitle: string;
  };
  callToActionSection: {
    image?: (number | null) | Media;
    title: string;
    description: string;
  };
  pricesPage: {
    pageTitle: string;
    pageDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workingHours".
 */
export interface WorkingHour {
  id: number;
  schedule: {
    days: string;
    hours: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  menuItems?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  contactButtonText?: T;
  showInHeader?: T;
  showInMobileMenu?: T;
  footerMenuTitle?: T;
  showContactsInFooter?: T;
  showWorkingHours?: T;
  workingHoursTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  address?: T;
  addressMapLink?: T;
  phone?: T;
  addressLabel?: T;
  phoneLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_select".
 */
export interface ContentSelect<T extends boolean = true> {
  navigationMenu?:
    | T
    | {
        home?: T;
        doctors?: T;
        services?: T;
        feedbacks?: T;
        blog?: T;
        prices?: T;
      };
  homePage?:
    | T
    | {
        welcomeImage?: T;
        welcomeDescription?: T;
        aboutImage?: T;
        aboutTitle?: T;
        aboutDescription?: T;
        missionTitle?: T;
        missionDescription?: T;
        servicesTitle?: T;
        servicesDescription?: T;
        ctaTitle?: T;
        ctaDescription?: T;
        feedbacksTitle?: T;
        blogTitle?: T;
        blogButton?: T;
        contactTitle?: T;
      };
  doctorsPage?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
      };
  blogPage?:
    | T
    | {
        backgroundImage?: T;
        pageTitle?: T;
        pageDescription?: T;
        articlesTitle?: T;
        faqTitle?: T;
      };
  callToActionSection?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
      };
  pricesPage?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workingHours_select".
 */
export interface WorkingHoursSelect<T extends boolean = true> {
  schedule?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}