/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    articles: Article;
    doctors: Doctor;
    services: Service;
    feedbacks: Feedback;
    socials: Social;
    questions: Question;
    schedule: Schedule;
    'service-prices': ServicePrice;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    'service-prices': ServicePricesSelect<false> | ServicePricesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    siteSettings: SiteSetting;
    contacts: Contact;
    scrollModal: ScrollModal;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    scrollModal: ScrollModalSelect<false> | ScrollModalSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Користувачі адмін-панелі
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Ім'я користувача (опціонально)
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  sections?:
    | (
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro-1';
          }
        | {
            title: string;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro-2';
          }
        | {
            title: string;
            description: string;
            image: number | Media;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            title?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            title?: string | null;
            articlesCount?: number | null;
            showMoreLink?: boolean | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-grid';
          }
        | {
            title?: string | null;
            /**
             * Виберіть статті для відображення
             */
            articles: (number | Article)[];
            buttonText?: string | null;
            /**
             * Введіть посилання на сторінку блогу. Якщо посилання не введено, кнопка не відображатиметься.
             */
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-row';
          }
        | {
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feedbacks';
          }
        | {
            title?: string | null;
            description?: string | null;
            image?: (number | null) | Media;
            showImage?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'description';
          }
        | {
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'doctors';
          }
        | {
            backgroundImage?: (number | null) | Media;
            title?: string | null;
            description?: string | null;
            /**
             * Вмикає напівпрозорий білий фон поверх зображення для кращої читабельності тексту
             */
            showOverlay?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-hero';
          }
        | {
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prices';
          }
        | {
            title?: string | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-info';
          }
      )[]
    | null;
  /**
   * Наприклад: /blog або /about. Обов'язково починається з /
   */
  path: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Бібліотека зображень та файлів
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Опис зображення для доступності та SEO (рекомендовано для всіх зображень)
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Статті та публікації блогу
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Заголовок статті, який відображається на сторінці та в списку статей
   */
  title: string;
  /**
   * Головне зображення статті (рекомендовано 1200x630px)
   */
  image: number | Media;
  /**
   * Тільки опубліковані статті відображаються на сайті
   */
  status: 'draft' | 'published';
  /**
   * Основний текст статті з можливістю форматування
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Профілі лікарів та персоналу клініки
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  /**
   * Повне ім'я лікаря або співробітника
   */
  name: string;
  /**
   * Професійне фото лікаря (рекомендовано квадратний формат, мінімум 400x400px)
   */
  photo: number | Media;
  /**
   * Спеціалізація або посада в клініці
   */
  position: string;
  /**
   * Скільки років працює лікар
   */
  experience: string;
  /**
   * Тільки опубліковані профілі відображаються на сайті
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Коротка назва послуги, яка відображатиметься на сайті
   */
  title: string;
  /**
   * Детальний опис послуги для відвідувачів
   */
  description: string;
  /**
   * Завантажте іконку для послуги (рекомендовано SVG або PNG)
   */
  icon: number | Media;
  /**
   * Тільки опубліковані послуги відображаються на сайті
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Відгуки та testimonials пацієнтів
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  /**
   * Повне ім'я або ініціали пацієнта
   */
  clientName: string;
  /**
   * Оберіть кількість зірок від 1 до 5
   */
  stars: number;
  /**
   * Текст відгуку пацієнта про лікування
   */
  content: string;
  /**
   * Тільки опубліковані відгуки відображаються на сайті
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Посилання на соціальні мережі клініки
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  /**
   * Назва соціальної мережі або месенджера
   */
  title: string;
  /**
   * Повне посилання на профіль у соціальній мережі
   */
  link: string;
  /**
   * Іконка соціальної мережі (рекомендовано SVG, 24x24px або більше)
   */
  icon: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  /**
   * Часте питання від пацієнтів
   */
  question: string;
  /**
   * Детальна відповідь на питання
   */
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Графік роботи клініки
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  /**
   * День тижня або період (наприклад, Понеділок-П'ятниця, Субота)
   */
  days: string;
  /**
   * Години роботи для вказаних днів
   */
  hours: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Детальний прайс-лист послуг
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-prices".
 */
export interface ServicePrice {
  id: number;
  /**
   * Конкретна процедура або вид послуги
   */
  title: string;
  /**
   * Вартість процедури (можна вказати діапазон або текст)
   */
  price: string;
  /**
   * Оберіть послугу, до якої відноситься ця ціна
   */
  serviceId: number | Service;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'socials';
        value: number | Social;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'schedule';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'service-prices';
        value: number | ServicePrice;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: number | PayloadKv;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        'intro-1'?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        'intro-2'?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'blog-grid'?:
          | T
          | {
              title?: T;
              articlesCount?: T;
              showMoreLink?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        'blog-row'?:
          | T
          | {
              title?: T;
              articles?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        feedbacks?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              showImage?: T;
              id?: T;
              blockName?: T;
            };
        description?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        doctors?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'blog-hero'?:
          | T
          | {
              backgroundImage?: T;
              title?: T;
              description?: T;
              showOverlay?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        prices?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'contact-info'?:
          | T
          | {
              title?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
      };
  path?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  status?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  position?: T;
  experience?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  clientName?: T;
  stars?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  title?: T;
  link?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  days?: T;
  hours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-prices_select".
 */
export interface ServicePricesSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  serviceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Глобальні налаштування хедера, футера та навігації
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Використовується в хедері та футері
   */
  menuItems?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SVG або PNG (рекомендовано SVG для чіткості)
   */
  logo: number | Media;
  /**
   * Відображається в хедері та мобільному меню
   */
  contactButtonText: string;
  /**
   * Текст над пунктами меню у футері
   */
  footerMenuTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Clinic contact information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  address: string;
  addressMapLink: string;
  phone: string;
  addressLabel?: string | null;
  phoneLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Налаштування модального вікна, що з'являється при скролі
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scrollModal".
 */
export interface ScrollModal {
  id: number;
  /**
   * Зображення для модального вікна (рекомендовано 400x400px)
   */
  image?: (number | null) | Media;
  /**
   * Основний заголовок модального вікна
   */
  title: string;
  /**
   * Опис під заголовком
   */
  description: string;
  /**
   * Чи показувати модальне вікно на сайті
   */
  isEnabled?: boolean | null;
  /**
   * Відсоток прокрутки від верху сторінки (0-100%). Користувач спочатку повинен проскролити до цього значення.
   */
  scrollDownTrigger: number;
  /**
   * Відсоток прокрутки від верху сторінки (0-100%). Після досягнення першого тригера, користувач повинен проскролити до цього значення.
   */
  scrollUpTrigger: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  logo?: T;
  contactButtonText?: T;
  footerMenuTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  address?: T;
  addressMapLink?: T;
  phone?: T;
  addressLabel?: T;
  phoneLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scrollModal_select".
 */
export interface ScrollModalSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  description?: T;
  isEnabled?: T;
  scrollDownTrigger?: T;
  scrollUpTrigger?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}